### ISSUE TITLE
[Documentation] README.md need to mention about permission

### ISSUE THREAD

**Issue by kwanguuuu** [flutter-moum/flutter_screenshot_callback#14]
When people use our plugin, they must add permission on their app 

So, I think we need to add information on our README.md for them
e.g:
<img width="691" alt="스크린샷 2019-10-07 오후 12 45 55" src="https://user-images.githubusercontent.com/18343294/66283969-a93b0500-e900-11e9-8b3a-19e28721f6bb.png">
<img width="682" alt="스크린샷 2019-10-07 오후 12 45 47" src="https://user-images.githubusercontent.com/18343294/66283970-a93b0500-e900-11e9-9c3b-a9e04beee6ad.png">

**Comment by beygee** [comment]
There is no need to add permission in iOS.

But in Android, We should add permission READ_EXTERNAL_STORAGE.

We will update README.md immediately.

Thank you
