### ISSUE TITLE
[IOS] Notification observer remove timing issue

### ISSUE THREAD

**Issue by yenoss** [flutter-moum/flutter_screenshot_callback#16]
## Description of the issue
The screenshot callback plugin has a `dispose` method. 

But the observer will be not releasing when the `dispose` method. 
This is because the observer is released when `deinit` is called from ios code.
This logic will be different from what the plugin's user expects.

So I think this should be fixed.

Thanks.

**Comment by songyiYu** [comment]
@minsub0922
