### ISSUE TITLE
Error android 9

### ISSUE THREAD

**Issue by JonnyBorges** [flutter-moum/flutter_screenshot_callback#17]
The project do not compile with the plugin on pubspec. 
I have the error:

/opt/flutter/.pub-cache/hosted/pub.dartlang.org/screenshot_callback-1.0.1/android/src/main/java/com/flutter/moum/screenshot_callback/ScreenshotCallbackPlugin.java:45: error: incompatible types: ArrayList<File> cannot be converted to String
                fileObserver = new FileObserver(files, FileObserver.CREATE) {
                                                ^
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/screenshot_callback-1.0.1/android/src/main/java/com/flutter/moum/screenshot_callback/ScreenshotCallbackPlugin.java:45: error: cannot find symbol
                fileObserver = new FileObserver(files, FileObserver.CREATE) {
                               ^
  symbol: constructor (ArrayList<File>,int)

**Comment by anysunflower** [comment]
meet the problem too, any work around?
