### ISSUE TITLE
ArrayList<File> cannot be converted to String

### ISSUE THREAD

**Issue by candrawardana** [flutter-moum/flutter_screenshot_callback#22]
C:\Users\Bungkus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\screenshot_callback-1.0.1\android\src\main\java\com\flutter\moum\screenshot_callback\ScreenshotCallbackPlugin.java:45: error: incompatible types: ArrayList<File> cannot be converted to String
                fileObserver = new FileObserver(files, FileObserver.CREATE) {
                                                ^
C:\Users\Bungkus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\screenshot_callback-1.0.1\android\src\main\java\com\flutter\moum\screenshot_callback\ScreenshotCallbackPlugin.java:45: error: cannot find symbol
                fileObserver = new FileObserver(files, FileObserver.CREATE) {
                               ^
  symbol: constructor (ArrayList<File>,int)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':screenshot_callback:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by beygee** [comment]
Please reopen the issue if you still get an error.

Thank you.
