### ISSUE TITLE
The package is locked to an older version of permission handler

### ISSUE THREAD

**Issue by v3rron** [flutter-moum/flutter_screenshot_callback#26]
Hi, please update the permission_handler dependency to newer version, otherwise it throws an error in projects that already have newer versions of permission_handler. 

It would be ideal if this package was not depending on permission_handler at all. I'd suggest instead providing documentation on which permissions should be enabled prior to using this package.

Here's the error log:
```
Because screenshot_callback >=1.1.1 depends on permission_handler ^4.0.0 and project depends on permission_handler ^5.0.1, screenshot_callback >=1.1.1 is forbidden.

So, because project depends on screenshot_callback ^1.1.1, version solving failed.
pub get failed (1; So, because project depends on screenshot_callback ^1.1.1, version solving failed.)
exit code 1
```

**Comment by iberatkaya** [comment]
I completely agree with you. The optimal would be to completely remove permission_handler from this package. I have checked the [pubspec.yaml](https://github.com/flutter-moum/flutter_screenshot_callback/blob/master/pubspec.yaml) file and noticed they have updated permission_handler to 5.0.1. Upon inspecting the published package on pub.dev, I noticed that the package is still using 4.0.0, so they have not published this package yet. I am now directly getting the [package from git](https://dart.dev/tools/pub/dependencies#git-packages) like this: 
```
  screenshot_callback:
    git: https://github.com/flutter-moum/flutter_screenshot_callback.git
```
Now the plugin is using permission_handler version 5.0.1.
