### ISSUE TITLE
Problem with PermissionHandler lib

### ISSUE THREAD

**Issue by pfelipe96** [flutter-moum/flutter_screenshot_callback#27]
Because screenshot_callback 1.1.1 depends on permission_handler ^4.0.0 and mobile_ahazou depends on permission_handler 5.0.1+1, screenshot_callback 1.1.1 is forbidden.

So, because mobile_ahazou depends on screenshot_callback 1.1.1, version solving failed.
pub get failed (1; So, because mobile_ahazou depends on screenshot_callback 1.1.1, version solving failed.)

**Comment by Zazo032** [comment]
You'll have to upgrade `permission_handler` dependency to latest on `mobile_ahazou`'s plugin
