### ISSUE TITLE
Getting error on iOS platform

### ISSUE THREAD

**Issue by priteshmetafic** [flutter-moum/flutter_screenshot_callback#31]
Hello, 
I cloned this repo and tried running example but I got an error so had to change the method.
Now when I try to run the project it gives me an error:
`An Observatory debugger and profiler on iPhone 11 Pro Max is available at:
http://127.0.0.1:58471/qaWFyHp7cUk=/
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel flutter.moum/screenshot_callback)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>`

I am attaching both screenshots.

![WhatsApp Image 2020-10-11 at 6 27 26 PM](https://user-images.githubusercontent.com/70843368/95719407-64714900-0c8d-11eb-9347-8b7bd74cd2c8.jpeg)

<img width="1657" alt="Screenshot 2020-10-12 at 1 16 09 PM" src="https://user-images.githubusercontent.com/70843368/95719272-33911400-0c8d-11eb-8ec7-9ba3b8e8455a.png">

**Comment by Joseph-Nathan** [comment]
any new news ?
