### ISSUE TITLE
When i do a Screenshot nothing happens !

### ISSUE THREAD

**Issue by freshtim** [flutter-moum/flutter_screenshot_callback#33]
I used the example file.
When I do a screenshot there should be a text printed to console and the text in the body should change. But nothing happens, I tried it on an android emulator and on my phone, also android.

If you need more information to solve this issue please tell me !

**Comment by Nemasio** [comment]
Same is happening to me. Not working. I debugged the code, and i know i effectivly gave permissions previusly, and that the listener is set correctly as the example.
But when doing screenshot on emulator or real device, nothing happens (no print, no snackbar), the listener doesnt respond.

**Comment by giovannilima262** [comment]
Same is happening to me.

**Comment by guilhermeagostinelli** [comment]
Same here.

**Comment by beygee** [comment]
@freshtim 

Please forgive me for being late.  From now on I will work hard on maintenance.

Maybe emulator couldn't detect screenshot callback. So you should use the physical device for testing.

Could you tell me the OS environment you used for the test?

**Comment by giovannilima262** [comment]
MacOS and Windows, but this problem occurred on the physical device

**Comment by RohithKilaparthi** [comment]
@beygee The build issue is gone now with the recent update, but the screen shot is not getting detected on any of the physical devices (both android and iOS)

**Comment by RohithKilaparthi** [comment]
Hi @beygee, any update?

**Comment by mg120** [comment]
the screenshot is not getting detected on any device(simulator, or physical device) ios specially, any solution?

**Comment by cristobalrodbar** [comment]
On Android try adding the following line under your application tag in manifest: 
` android:requestLegacyExternalStorage="true" `

**Comment by beygee** [comment]
Fixed 2.0.0.
Sorry for being late.
