### ISSUE TITLE
MissingPluginException(No implemention found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by zhangjun920912** [flutter-moum/flutter_screenshot_callback#45]
When I use this plugin to add listener for screenShot, I got this error on Android "MissingPluginException(No implemention found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)", I didn't know how to resolve this issue,error information like under :
<img width="700" alt="Screen Shot 2021-05-07 at 7 19 43 PM" src="https://user-images.githubusercontent.com/17971736/117442416-50fb3780-af69-11eb-8213-a740fab7714f.png">
![0zm40120008n8rmzy3791](https://user-images.githubusercontent.com/17971736/117442440-5789af00-af69-11eb-8a35-bd38eadef181.jpg)
![0zm03120008n8qob8A16B](https://user-images.githubusercontent.com/17971736/117442452-5b1d3600-af69-11eb-94be-dd6cfe8f9f28.jpg)

**Comment by ousvat** [comment]
@zhangjun920912 on what device this error appears?
