### ISSUE TITLE
The plugins `screenshot_callback` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by imajercsik** [flutter-moum/flutter_screenshot_callback#53]
With the new flutter version 2.5.0 i am getting this after running flutter pub get:

Running "flutter pub get" in hyll-mobile...                         4.9s
The plugins `screenshot_callback` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by wrteam-priyansh** [comment]
@imajercsik any update on this issue?

**Comment by amitmishra7** [comment]
Facing same issue. Also the dependencies are older ones.

**Comment by bulgarian-beast** [comment]
Same

**Comment by beygee** [comment]
Fixed 2.0.0.
Sorry for being late.
