### ISSUE TITLE
Android not listen to capture 

### ISSUE THREAD

**Issue by JumanDhaher** [flutter-moum/flutter_screenshot_callback#56]
ios work
but android not work?

**Comment by beygee** [comment]
Can you test again with version 2.0.0?
If the error still persists, please reopen the issue.

**Comment by JumanDhaher** [comment]
It is still not work

**Comment by vankhai1997** [comment]
> It is still not work

I have same issue in android, but I was fixed it, u can check. 
https://github.com/vankhai1997/screenshot_callback.git
