### ISSUE TITLE
Specific version of androidx.core:core need to be declared in build.gradle

### ISSUE THREAD

**Issue by ZhuBoao** [flutter-moum/flutter_screenshot_callback#57]
Currently in `/android/build.gradle`, there is implementation dependency `androidx.core:core-ktx` which has no specific version.
```
dependencies {
    implementation "androidx.core:core-ktx:+"
    ...
}
```
This leads gradle to automatically download the latest version of [AndroidX Core](https://developer.android.com/jetpack/androidx/releases/core)(currently 1.9.0) and may cause issue when plugin user trying to build Android APK.

Here is a example of error caused:
```
* What went wrong:
Execution failed for task ':screenshot_callback:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/leonardo/.gradle/caches/transforms-3/13f9f90ed26e8ba6924d64da8adfcfbe/transformed/core-1.9.0-alpha04/res/values/values.xml:104:5-113:25: AAPT: error: resource android:attr/lStar not found.
```

I have tried on the example app the build also failed. To fix this issue the plugin needs to specify the version to the correct `1.6.0`.

```
dependencies {
    implementation "androidx.core:core-ktx:1.6.0"
    ...
}
```
After this change, building APK will succeed.

**Comment by beygee** [comment]
Fix stable version 1.7.0. Thank you
