### ISSUE TITLE
Build Android release failed [version 2.0.3]

### ISSUE THREAD

**Issue by bossxomlut** [flutter-moum/flutter_screenshot_callback#85]
Execution failed for task ':screenshot_callback:verifyReleaseResources'. > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action > Android resource linking failed ERROR:/Users/vinhngo/flutter_screenshot/build/screenshot_callback/intermediates/merged_res/release/values/values.xml:132: AAPT: error: resource android:attr/lStar not found.

**Comment by jusuf-el** [comment]
@1712916 was this solved? If yes, how? Thank you!
